# Generated by Django 5.2.9 on 2025-12-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identificador único en los correos (ej: últimos 4 dígitos de la tarjeta)', max_length=50, null=True),
        ),
    ]
