# Generated by Django 5.2.9 on 2025-12-04 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budget.category')),
            ],
            options={
                'indexes': [models.Index(fields=['month', 'category'], name='budget_budg_month_a49fb3_idx')],
                'unique_together': {('category', 'month')},
            },
        ),
    ]
