# Generated by Django 5.2.9 on 2025-12-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
