# Generated by Django 5.2.9 on 2025-12-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_category',
            field=models.OneToOneField(blank=True, help_text='Categoría interna para gestionar el pago de esta tarjeta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_account', to='budget.category'),
        ),
    ]
