# Generated by Django 5.2.9 on 2025-12-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_account_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='off_budget',
            field=models.BooleanField(default=False, help_text='Si es True, el saldo no suma al presupuesto y las transferencias hacia aquí requieren categoría.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Cuenta Corriente / Vista'), ('SAVINGS', 'Ahorro'), ('CREDIT', 'Tarjeta de Crédito'), ('CASH', 'Efectivo'), ('ASSET', 'Activo (Inversión/Bien)'), ('LOAN', 'Pasivo (Deuda/Préstamo)')], default='CHECKING', max_length=10),
        ),
    ]
