# Generated by Django 5.2.9 on 2025-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_account_off_budget_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='goal_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='category',
            name='goal_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='goal_type',
            field=models.CharField(choices=[('NONE', 'Sin Meta'), ('MONTHLY', 'Ahorro Mensual Fijo'), ('TARGET_DATE', 'Alcanzar Saldo para Fecha'), ('TARGET_BALANCE', 'Mantener Saldo Mínimo')], default='NONE', max_length=20),
        ),
    ]
